default:
  image: circleci/node:12-buster-browsers

stages:
  - prepare
  - testing
  - build

# To cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/yarn"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/cypress"

# GitLab don't support bash syntax in the "variables" definitions,
# so we use a custom step to define all necessary environment variables
.defineVars: &defineVars |-
  export VERSION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}}"

###################
# Steps to extend #
###################

.yarnCache:
  cache:
    key: yarn-cache
    paths:
      - cache/cypress
      - node_modules
      - packages/*/node_modules
      - tests-e2e/node_modules
    policy: pull

#################
# Prepare stage #
#################

Yarn:
  stage: prepare
  extends:
    - .yarnCache
  cache:
    policy: pull-push
  script:
    - yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

#################
# Testing stage #
#################

Lint:
  stage: testing
  extends:
    - .yarnCache
  script:
    - yarn lint:check

TypeScript:
  stage: testing
  extends:
    - .yarnCache
  script:
    - yarn ts:check

Jest:
  stage: testing
  extends:
    - .yarnCache
  script:
    - yarn test

Cypress:
  stage: testing
  extends:
    - .yarnCache
  variables:
    # Sentry's DSN is provided for build step from repository configuration,
    # but it's not necessary to send any logs reports during E2E testing
    SENTRY_DSN: ""
  script:
    - yarn start &
    - yarn wait-on http://localhost:8080
    - >
      yarn --cwd tests-e2e test:ci
      --record
      --browser chrome
      --parallel
  parallel: 4
  allow_failure: true

###############
# Build stage #
###############

Build:
  stage: build
  needs:
    - Lint
    - TypeScript
    - Jest
  extends:
    - .yarnCache
  before_script:
    - *defineVars
  script:
    - yarn build
  artifacts:
    name: "Production build for $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    paths:
      - build
    expire_in: 1 week
