language: node_js
node_js:
  - "11"

cache: yarn

jobs:
  include:
    - stage: Test
      name: Lint
      script: yarn lint
    - name: Flow
      script: yarn flow
    - name: Test
      script: yarn test

    - stage: Build
      name: Build production assets
      script: yarn build
