language: node_js
node_js:
  - "11"

cache: yarn

addons:
  ssh_known_hosts: account.ely.by

script:
  - yarn lint
  - yarn flow
  - yarn test
  - yarn build:quiet

before_deploy:
  - openssl aes-256-cbc -K $encrypted_dd5ad7a5f201_key -iv $encrypted_dd5ad7a5f201_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: scp -rp $TRAVIS_BUILD_DIR/dist/* deploy@account.ely.by:/var/deploy/accounts-frontend/
  on:
    branch: master
