// flow-typed signature: f7ed1ad96a453a021e6d98c1d144ef43
// flow-typed version: <<STUB>>/react-motion_v0.5.x/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-motion/build/react-motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/mapToZero' {
  declare module.exports: any;
}

declare module 'react-motion/lib/mergeDiff' {
  declare module.exports: any;
}

declare module 'react-motion/lib/Motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/presets' {
  declare module.exports: any;
}

declare module 'react-motion/lib/react-motion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/reorderKeys' {
  declare module.exports: any;
}

declare module 'react-motion/lib/shouldStopAnimation' {
  declare module.exports: any;
}

declare module 'react-motion/lib/spring' {
  declare module.exports: any;
}

declare module 'react-motion/lib/StaggeredMotion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/stepper' {
  declare module.exports: any;
}

declare module 'react-motion/lib/stripStyle' {
  declare module.exports: any;
}

declare module 'react-motion/lib/TransitionMotion' {
  declare module.exports: any;
}

declare module 'react-motion/lib/Types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-motion/build/react-motion.js' {
  declare module.exports: $Exports<'react-motion/build/react-motion'>;
}
declare module 'react-motion/lib/mapToZero.js' {
  declare module.exports: $Exports<'react-motion/lib/mapToZero'>;
}
declare module 'react-motion/lib/mergeDiff.js' {
  declare module.exports: $Exports<'react-motion/lib/mergeDiff'>;
}
declare module 'react-motion/lib/Motion.js' {
  declare module.exports: $Exports<'react-motion/lib/Motion'>;
}
declare module 'react-motion/lib/presets.js' {
  declare module.exports: $Exports<'react-motion/lib/presets'>;
}
declare module 'react-motion/lib/react-motion.js' {
  declare module.exports: $Exports<'react-motion/lib/react-motion'>;
}
declare module 'react-motion/lib/reorderKeys.js' {
  declare module.exports: $Exports<'react-motion/lib/reorderKeys'>;
}
declare module 'react-motion/lib/shouldStopAnimation.js' {
  declare module.exports: $Exports<'react-motion/lib/shouldStopAnimation'>;
}
declare module 'react-motion/lib/spring.js' {
  declare module.exports: $Exports<'react-motion/lib/spring'>;
}
declare module 'react-motion/lib/StaggeredMotion.js' {
  declare module.exports: $Exports<'react-motion/lib/StaggeredMotion'>;
}
declare module 'react-motion/lib/stepper.js' {
  declare module.exports: $Exports<'react-motion/lib/stepper'>;
}
declare module 'react-motion/lib/stripStyle.js' {
  declare module.exports: $Exports<'react-motion/lib/stripStyle'>;
}
declare module 'react-motion/lib/TransitionMotion.js' {
  declare module.exports: $Exports<'react-motion/lib/TransitionMotion'>;
}
declare module 'react-motion/lib/Types.js' {
  declare module.exports: $Exports<'react-motion/lib/Types'>;
}
